version: "3.9"

services:
  jaeger:
    container_name: jaeger
    hostname: hostname
    image: jaegertracing/opentelemetry-all-in-one
    volumes:
      - ./jaeger/data:/data
    ports:
      - 13133:13133
      - 16686:16686
      - 4317:55680
    restart: unless-stopped
    networks:
      - default
networks:
  default:
    name: networkname
    external: false
