version: "3.8"

services:
   seq:
    container_name: seq
    image: datalust/seq:latest
    volumes:
        - data:/data
    ports:
      - 5341:80
    restart: always
    environment:
      - ACCEPT_EULA=Y
    networks:
       - default
volumes:
  data:

networks:
   default:
     name: seq
     external: false