version: "3.9"

services:
  seq:
    container_name: seq
    hostname: hostname
    image: datalust/seq:latest
    volumes:
      - ./seq/data:/data
    ports:
      - 8081:80
      - 5341:5341
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
    networks:
      - default
networks:
  default:
    name: networkname
    external: false
