version: '3.8'
services:
    mysqlserver:
        container_name: mysqlserver
        image: mysql:latest
        volumes:
          - mysql-server-data:/var/lib/mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: 1234567890
        ports:
            - '3306:3306'
        networks: 
         - default
    phpmyadmin:
      container_name: phpmyadmin
      image: phpmyadmin:latest
      restart: always
      environment:
        PMA_HOST: mysqlserver
      depends_on:
        - mysqlserver
      ports:
        - '8080:80'
      networks:
       - default
volumes:
    mysql-server-data:

networks:
  default:
    name: mysqlserver
    external: false