version: "3.9"

networks:
    mylab.local:
        external: true
        
services:

    #ref: https://hub.docker.com/_/microsoft-mssql-server
    mssql-server:
        container_name: mssql-server
        hostname: acer-rubrum
        image: mcr.microsoft.com/mssql/server:2022-latest
        volumes:
            - ./mssql/data:/var/opt/mssql/data
            - ./mssql/log:/var/opt/mssql/log
            - ./mssql/secrets:/var/opt/mssql/secrets
            - ./mssql/backups:/var/backups
        ports:
            - 1433:1433
        environment:
            - ACCEPT_EULA=Y
            - MSSQL_SA_PASSWORD=1234567890
            - MSSQL_PID=Express
        networks:
            - mylab.local
        restart: unless-stopped
        healthcheck:
            test:
                [
                    "CMD-SHELL",
                    "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P $$MSSQL_SA_PASSWORD -Q 'SELECT 1' || exit 1"
                ]
            interval: 59s
            retries: 10
            start_period: 10s
            timeout: 3s

    #ref: https://hub.docker.com/r/bitnami/mysql
    mysql-server:
        container_name: mysql-server
        hostname: pinus-strobus
        image: bitnami/mysql:latest
        environment:
            - MYSQL_ROOT_PASSWORD=1234567890
        ports:
            - 3306:3306
        volumes:
            - ./mysql:/bitnami/mysql
        restart: unless-stopped
        healthcheck:
            test:
                [
                    "CMD-SHELL",
                    "/usr/bin/mysql -uroot -p$$MYSQL_ROOT_PASSWORD -hlocalhost mysql -e 'SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES LIMIT 1;' || exit 1"
                ]
            interval: 59s
            timeout: 5s
            retries: 5
            start_period: 30s
        networks:
            - mylab.local
    
    #ref: https://hub.docker.com/_/mariadb
    # mariadb-server:
    #     container_name: mariadb-server
    #     hostname: betula-lenta
    #     image: mariadb:latest
    #     environment:
    #         - MYSQL_ROOT_PASSWORD=1234567890
    #     ports:
    #         - 3306:3306
    #     volumes:
    #         - ./mariadb/data:/var/lib/mysql
    #     restart: unless-stopped
    #     healthcheck:
    #         test:
    #             [
    #                 "CMD-SHELL",
    #                 "/usr/bin/mysql -uroot -p$$MYSQL_ROOT_PASSWORD -hlocalhost mysql -e 'SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES LIMIT 1;' || exit 1"
    #             ]
    #         interval: 59s
    #         timeout: 5s
    #         retries: 5
    #         start_period: 30s
    #     networks:
    #         - mylab.local

    #ref: https://hub.docker.com/r/bitnami/phpmyadmin
    phpmyadmin:
        container_name: phpmyadmin
        hostname: ulmus-rubra
        image: bitnami/phpmyadmin:latest
        ports:
            - 8080:8080
        environment:
            - DATABASE_HOST=pinus-strobus
        depends_on:
            - mysql-server
            # - mariadb-server
        restart: unless-stopped
        networks:
            - mylab.local

    #ref: https://hub.docker.com/r/datalust/seq
    seq:
        container_name: seq
        hostname: picea-rubens
        image: datalust/seq:latest
        volumes:
            - ./seq/data:/data
        ports:
            - 8081:80
            - 5341:5341
        environment:
            - ACCEPT_EULA=Y
        networks:
            - mylab.local
        restart: unless-stopped
    
    #ref: https://hub.docker.com/r/bitnami/redis
    redis-cache:
        container_name: redis-cache
        hostname: carya-ovata
        image: bitnami/redis:latest
        volumes:
            - ./redis/data:/bitnami/redis/data
        ports:
            - 6379:6379
        environment:
            ALLOW_EMPTY_PASSWORD: yes
        networks:
            - mylab.local
        restart: unless-stopped