version: "3.9"

services:
    mssql-server:
        container_name: mssql-server
        hostname: acer-rubrum
        image: mcr.microsoft.com/mssql/server:2022-latest
        volumes:
            - ./mssql/data:/var/opt/mssql/data
            - ./mssql/log:/var/opt/mssql/log
            - ./mssql/secrets:/var/opt/mssql/secrets
            - ./mssql/backups:/var/backups
        ports:
            - 1433:1433
        environment:
            - ACCEPT_EULA=Y
            - MSSQL_SA_PASSWORD=1234567890
            - MSSQL_PID=Express
        networks:
            - default
        restart: unless-stopped
        healthcheck:
            test:
                [
                    "CMD-SHELL",
                    "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P $$MSSQL_SA_PASSWORD -Q 'SELECT 1' || exit 1"
                ]
            interval: 59s
            retries: 10
            start_period: 10s
            timeout: 3s
    # mariadb-server:
    #     container_name: mariadb-server
    #     hostname: betula-lenta
    #     image: mariadb:latest
    #     environment:
    #         - MYSQL_ROOT_PASSWORD=1234567890
    #     ports:
    #         - 3306:3306
    #     volumes:
    #         - ./mariadb/data:/var/lib/mysql
    #     restart: unless-stopped
    #     healthcheck:
    #         test:
    #             [
    #                 "CMD-SHELL",
    #                 "/usr/bin/mysql -uroot -p$$MYSQL_ROOT_PASSWORD -hlocalhost mysql -e 'SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES LIMIT 1;' || exit 1"
    #             ]
    #         interval: 59s
    #         timeout: 5s
    #         retries: 5
    #         start_period: 30s
    #     networks:
    #         - default
    # adminer:
    #     container_name: adminer
    #     hostname: ulmus-rubra
    #     image: adminer
    #     ports:
    #         - 8080:8080
    #     environment:
    #         ADMINER_DEFAULT_SERVER: betula-lenta
    #         ADMINER_DESIGN: lucas-sandery
    #     depends_on:
    #         - mariadb-server
    #         - mssql-server
    #     restart: unless-stopped
    #     networks:
    #         - default
    seq:
        container_name: seq
        hostname: picea-rubens
        image: datalust/seq:latest
        volumes:
            - ./seq/data:/data
        ports:
            - 8081:80
            - 5341:5341
        environment:
            - ACCEPT_EULA=Y
        networks:
            - default
        restart: unless-stopped
    cache:
        container_name: redis
        hostname: carya-ovata
        image: bitnami/redis:latest
        volumes:
            - ./redis/data:/data
        ports:
            - 6379:6379
        environment:
            ALLOW_EMPTY_PASSWORD: yes
        networks:
            - default
        restart: unless-stopped
networks:
    default:
        name: mylab.local
        external: false
